# Site wide configuration
title:       "Blog de Benoit Galati"
description: "#Linux #Dév #Tech ..et plus si affinités"
locale:      fr_FR
# logo: site-logo.png
# url: http://localhost:4000
search:   true
comments: true
mathjax:  true

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

timezone: Europe/Paris
future:   true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Benoit Galati
  avatar: # 1414963961_linux_tux-512.png
  email: benoit.galati@gmail.com
  disqus-shortname: b-galati
  twitter: B_Galati
  facebook: #username
  github: B-Galati
  stackexchange: #http://stackoverflow.com/users/4173130/benoit-galati
  linkedin: benoit-galati-8719a74a
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
