#theme: jekyll-theme-so-simple
#remote_theme: "mmistakes/so-simple-theme"
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Benoit Galati"
description: "Blog #Linux #Dev #Tech ...and more"
baseurl: null # the subpath of your site, e.g. "/blog"
url: https://www.bgalati.fr
logo: #/images/avatar.jpg # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: true # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: b-galati # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: B_Galati # site's Twitter username, e.g. "mmistakes"
timezone: Europe/Paris
future: true

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: feed.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - config.rb
  - Rakefile
  - LICENCE
  - README.md
  - bin/
  - package.json
  - package-lock.json
  - .idea/
  - docker-compose.yml
  - banner.js
  - .editorconfig
  - .gitattributes
  - .gitignore
  - .ssl/
  - _config.yml
  - Makefile

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Benoit Galati
  picture: /images/avatar.jpg
  email: benoit.galati@gmail.com
  twitter: B_Galati
  links:
    - title: GitHub
      url: https://github.com/B-Galati
      icon: fab fa-github
    - title: Twitter
      url: https://twitter.com/B_Galati
      icon: fab fa-twitter
    - title: Symfony Connect
      url: https://connect.symfony.com/profile/benoitgalati
      icon: fab fa-symfony
    - title: Stackoverflow
      url: http://stackoverflow.com/users/4173130/benoit-galati
      icon: fab fa-stack-overflow
    - title: Keybase
      url: https://keybase.io/bgalati
      icon: fab fa-keybase
    - title: LinkedIn
      url: https://www.linkedin.com/in/benoitgalati
      icon: fab fa-linkedin
#    - title: Patreon
#      url: https://www.patreon.com/user/creators?u=2547714
#      icon: fab fa-patreon

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/B-Galati
    icon: fab fa-github
  - title: Twitter
    url: https://twitter.com/B_Galati
    icon: fab fa-twitter
  - title: Symfony Connect
    url: https://connect.symfony.com/profile/benoitgalati
    icon: fab fa-symfony
  - title: Stackoverflow
    url: http://stackoverflow.com/users/4173130/benoit-galati
    icon: fab fa-stack-overflow
  - title: Keybase
    url: https://keybase.io/bgalati
    icon: fab fa-keybase
  - title: LinkedIn
    url: https://www.linkedin.com/in/benoitgalati
    icon: fab fa-linkedin
  - title: Patreon
    url: https://www.patreon.com/user/creators?u=2547714
    icon: fab fa-patreon
  - title: RSS Feed
    url: /feed.xml
    icon: fas fa-rss
