web:
    image: benoitg/ruby
    volumes:
        - ./:/usr/src/
        - ./bundle:/usr/local/bundle
    expose:
        - "4000"
    ports:
        - "4000:4000"
    environment:
        - DOCKER_UID
        - DOCKER_GID
    command: bundle exec jekyll serve --drafts --watch --force_polling --host '0.0.0.0'
