version: "3.4"
services:
  app:
    image: benoitg/ruby
    working_dir: /usr/src
    entrypoint: []
    volumes:
        - ./:/usr/src/
        - ./bundle/:/usr/local/bundle/
    environment:
        - DOMAIN_NAME=bgalati.docker
    user: ${HOST_UID}:${HOST_GID}
    command: bundle exec jekyll serve --drafts --watch --force_polling --host 'bgalati.docker' --ssl-cert .ssl/cert.crt --ssl-key .ssl/private.key
