version: "3.4"
services:
  app:
    image: benoitg/ruby
    volumes:
      - ./:/app
      - ~/.bundle/cache:/home/ruby/.bundle/cache
    environment:
      - DOMAIN_NAME=bgalati.docker
    command: bundle exec jekyll serve --drafts --watch --force_polling --host 'bgalati.docker' --ssl-cert .ssl/cert.crt --ssl-key .ssl/private.key
